### 1. Create Department 1
POST http://localhost:8080/api/departments
Content-Type: application/json

{
  "name": "HR"
}


### 2. Create Employee 1 in HR 
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "Alice",
  "lastName": "Brown",
  "email": "alice.brown@hr.com",
  "department": {
    "id": 1
  }
}


### 3. Create Employee 2 in IT
POST http://localhost:8080/api/employees
Content-Type: application/json

{
  "firstName": "Emily",
  "lastName": "Johnson",
  "email": "emily.johnson@it.com",
  "department": {
    "id": 1
  }
}

### 8. Get All Employees
GET http://localhost:8080/api/employees

### 9. Get Employee by Email (John Doe)
GET http://localhost:8080/api/employees/email/john.doe@hr.com

### 10. Get Employees by Last Name "Brown"
GET http://localhost:8080/api/employees/lastname/Brown

### 11. Get Employees by Department HR (ID = 1)
GET http://localhost:8080/api/employees/department/1


### 13. Get Number of Employees by Department
GET http://localhost:8080/api/employees/count-by-department
