-- 1. Connect to the database as SYSDBA
CONNECT SYS/"@NI_18_art"@"//localhost:1521/orcl" AS SYSDBA;

-- 2. Create the common user C##DB1 with the specified password
CREATE USER "C##DB1" IDENTIFIED BY "password_1234" CONTAINER=ALL;

-- 3. Grant the necessary privileges to the user
GRANT CONNECT, RESOURCE TO "C##DB1" CONTAINER=ALL;

-- 4. Grant unlimited quota on the USERS tablespace to the user
ALTER USER "C##DB1" QUOTA UNLIMITED ON USERS;

-- 5. Connect to the C##DB1 user (common user)
CONNECT "C##DB1"/"password_1234"@//localhost:1521/orcl;


ALTER SESSION SET CURRENT_SCHEMA = C##DB1;

-- Create DEPARTMENT Table in db1
CREATE TABLE DEPARTMENT (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

-- Insert departments in db1
INSERT INTO DEPARTMENT (NAME) VALUES ('HR');
INSERT INTO DEPARTMENT (NAME) VALUES ('Finance');
INSERT INTO DEPARTMENT (NAME) VALUES ('IT');

-- Create EMPLOYEE Table in db1
CREATE TABLE EMPLOYEE (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    DEPARTMENT_ID NUMBER,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- Insert employees in db1
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('John', 'Doe', 'john.doe@db1.com', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Janeffer', 'lawrance', 'jane.lawrance@db1.com', 1);

-- Insert employees into department 2
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Alice', 'Smith', 'alice.smith@db1.com', 2);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Bob', 'Johnson', 'bob.johnson@db1.com', 2);

-- Insert employees into department 3
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Charlie', 'Brown', 'charlie.brown@db1.com', 3);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Diana', 'Wilson', 'diana.wilson@db1.com', 3);

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;