-- 1. Connect to the database as SYSDBA
CONNECT SYS/"@NI_18_art"@"//localhost:1521/orcl" AS SYSDBA;

-- 2. Create the common user C##DB1 with the specified password
CREATE USER "C##DB2" IDENTIFIED BY "password_5678" CONTAINER=ALL;

-- 3. Grant the necessary privileges to the user
GRANT CONNECT, RESOURCE TO "C##DB2" CONTAINER=ALL;

-- 4. Grant unlimited quota on the USERS tablespace to the user
ALTER USER "C##DB2" QUOTA UNLIMITED ON USERS;

-- 5. Connect to the C##DB1 user (common user)
CONNECT "C##DB2"/"password_5678"@//localhost:1521/orcl;


ALTER SESSION SET CURRENT_SCHEMA = C##DB2;


-- Create DEPARTMENT Table in db2
CREATE TABLE DEPARTMENT (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

-- Insert departments in db2
INSERT INTO DEPARTMENT (NAME) VALUES ('Marketing');
INSERT INTO DEPARTMENT (NAME) VALUES ('Tester');
INSERT INTO DEPARTMENT (NAME) VALUES ('Developer');

-- Create EMPLOYEE Table in db1
CREATE TABLE EMPLOYEE (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    DEPARTMENT_ID NUMBER,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- Insert employees into department 1
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Grace', 'Taylor', 'grace.taylor@db2.com', 1);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Henry', 'Martin', 'henry.martin@db2.com', 1);

-- Insert employees into department 2
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Ivy', 'White', 'ivy.white@db2.com', 2);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Jack', 'Harris', 'jack.harris@db2.com', 2);

-- Insert employees into department 3
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Karen', 'Clark', 'karen.clark@db2.com', 3);

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) 
VALUES ('Leo', 'Lewis', 'leo.lewis@db2.com', 3);

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;